server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/0CHA
    username: root
    password: 12345678
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  #  thymeleaf:
  #    cache: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: E5bD_SOp2goX_aFabVyb
            client-secret: MSRmXK_d8C
            redirect-uri: http://localhost:8082/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: name, email
            client-name: Naver
          kakao:
            client-id: 8f754a044ed2c9b90cd39ab7c47f9f99
            client-secret: xRDsNSX98AKFx7SafJFal5mwKQvQ8vli
            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

base-domain:
  front: "http://localhost:8082"

logging:
  level:
#    org.hibernate.sql: INFO
    org.hibernate.orm.jdbc.bind: INFO

jwt:
  secretKey: D45D5084B9DSBSSBGWE4QFWDQSADWQIPQW123AS2DF3DA9SD0F73823BFDC31E2EAF2F
  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

